apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rinnguyen-groove/argocd-demo.git
    targetRevision: HEAD
    path: demo1/deploy
  destination: 
    server: https://kubernetes.default.svc
    namespace: demo1

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true