apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomize

resources:
  - ../../base

namePrefix: dev-
nameSuffix: ""

patches:
  - path: replica-patch.yml
    target:
      kind: Deployment
      name: todo