apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-todo-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rinnguyen-groove/argocd-demo.git
    targetRevision: HEAD
    path: demo2/overlays/prod
  destination: 
    server: https://192.168.147.5:6443
    namespace: demo2-prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true